services:
  app:
    build: .
    volumes:
      - .:/app  # Mount current project directory so db.json changes persist
    container_name: task-manager-qa-app
    ports:
      - "3000:3000"
    command: npm start

  tests:
    image: mcr.microsoft.com/playwright:v1.52.0-jammy
    container_name: task-manager-qa-tests
    working_dir: /tests
    volumes:
      - .:/tests
      - ./allure-results:/tests/allure-results
    command: npx playwright test --reporter=allure-playwright
    depends_on:
      - app
    network_mode: service:app
